# Generated by Django 5.2.7 on 2025-10-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.CharField(max_length=255)),
                ('resposta', models.CharField(max_length=255)),
                ('materia', models.CharField(max_length=100)),
                ('erro', models.TextField(max_length=4000)),
            ],
        ),
    ]
